config/routes.rb
Rails.application.routes.draw do
  resources :documents
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get '/documents_user/:user', to: 'documents#documents_of_user'
  
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/document.rb
class Document
  include Mongoid::Document
  include Mongoid::Timestamps
  field :name, type: String
  field :type, type: String
  field :user, type: String
  field :storage, type: String
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    skip_before_action :verify_authenticity_token
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  # skip_before_action :verify_authenticity_token
  before_action :set_document, only: %i[ show edit update destroy ]

  def ensure_tmp_dir_exists_for(filename)
    puts "ensure"
    Dir.mkdir File.dirname(filename)
    rescue Errno::EEXIST
  end

  # GET documents_user/:user
  def documents_of_user
    user = params["user"]
    @document = Document.where(:user => user)
    render json: @document
  end

  # GET /documents or /documents.json
  def index
    @documents = Document.all
  end

  # GET /documents/1 or /documents/1.json
  def show
  end

  # GET /documents/new
  def new
    @document = Document.new
  end

  # GET /documents/1/edit
  def edit
  end

  # POST /documents or /documents.json
  def create
    
    name = document_params[:name]
    user = document_params[:user]
    type = document_params[:type]

    file_base64 = params[:file]
    decode_base64_content = Base64.decode64(file_base64)
    encoded_name_file = "#{name}#{SecureRandom.hex(3)}.#{type}"
    filename = Rails.root.join(user, encoded_name_file)
    ensure_tmp_dir_exists_for filename
    File.open(filename, 'wb') do |f|
      f.write(decode_base64_content)
    end
    file = File.open(filename)
    
    require "google/cloud/storage"
    bucket_name = "unpdf_st"

    storage = Google::Cloud::Storage.new
    bucket  = storage.bucket bucket_name, skip_lookup: true
    bucket.create_file file, filename
    puts "Uploaded #{name} as #{filename} in bucket #{bucket_name}"
    new_document = { "name" => name, "type" => type, "user" => user, "storage" => filename }
    @document = Document.new(new_document)
    if @document.save
      render json: @document 
    else
      render json: @document.errors
    end
    # respond_to do |format|
    #   if @document.save
    #     format.html { redirect_to document_url(@document), notice: "Document was successfully created." }
    #     format.json { render :show, status: :created, location: @document }
    #   else
    #     format.html { render :new, status: :unprocessable_entity }
    #     format.json { render json: @document.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # PATCH/PUT /documents/1 or /documents/1.json
  def update
    respond_to do |format|
      if @document.update(document_params)
        format.html { redirect_to document_url(@document), notice: "Document was successfully updated." }
        format.json { render :show, status: :ok, location: @document }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1 or /documents/1.json
  def destroy
    @document.destroy

    respond_to do |format|
      format.html { redirect_to documents_url, notice: "Document was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_document
      @document = Document.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def document_params
      params.require(:document).permit(:name, :type, :user, :storage)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/_document.html.erb
<div id="<%= dom_id document %>">
  <p>
    <strong>Name:</strong>
    <%= document.name %>
  </p>

  <p>
    <strong>Type:</strong>
    <%= document.type %>
  </p>

  <p>
    <strong>User:</strong>
    <%= document.user %>
  </p>

  <p>
    <strong>Storage:</strong>
    <%= document.storage %>
  </p>

</div>

app/views/documents/_form.html.erb
<%= form_with(model: document) do |form| %>
  <% if document.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(document.errors.count, "error") %> prohibited this document from being saved:</h2>

      <ul>
        <% document.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :type, style: "display: block" %>
    <%= form.text_field :type %>
  </div>

  <div>
    <%= form.label :user, style: "display: block" %>
    <%= form.text_field :user %>
  </div>

  <div>
    <%= form.label :storage, style: "display: block" %>
    <%= form.text_area :storage %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/documents/edit.html.erb
<h1>Editing document</h1>

<%= render "form", document: @document %>

<br>

<div>
  <%= link_to "Show this document", @document %> |
  <%= link_to "Back to documents", documents_path %>
</div>

app/views/documents/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Documents</h1>

<div id="documents">
  <% @documents.each do |document| %>
    <%= render document %>
    <p>
      <%= link_to "Show this document", document %>
    </p>
  <% end %>
</div>

<%= link_to "New document", new_document_path %>

app/views/documents/new.html.erb
<h1>New document</h1>

<%= render "form", document: @document %>

<br>

<div>
  <%= link_to "Back to documents", documents_path %>
</div>

app/views/documents/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @document %>

<div>
  <%= link_to "Edit this document", edit_document_path(@document) %> |
  <%= link_to "Back to documents", documents_path %>

  <%= button_to "Destroy this document", @document, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>